name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04]
        dotnet: [8.0.300]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore tools
        run: dotnet tool restore

      - name: Run Build
        run: dotnet build

      - name: Run Tests
        run: dotnet test --no-build
